spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ad_mybatisplus?serverTimezone-UTC&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto
      table-prefix: tb_
      logic-delete-field: deleted
      logic-not-delete-value: 0
      logic-delete-value: 1

aliyun:
  oss:
    access-key-id: LTAI5tH6HKinBooaELQiKn4R
    access-key-secret: vU2wTbDgSHLQIr52ZlLaOCCukh3WwH
    bucket-name: web-advertisement
    endpoint: aliyun.oss.endpoint="https://oss-cn-hangzhou.aliyuncs.com"
